application: simple-paint-js
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /script
  static_dir: script
- url: /.*
  script: paintapp.app

libraries:
- name: jinja2
  version: latest

